{
    'name': 'Bista HMS Emergency & IPD',
    'version': '19.0.1.0.0',
    'category': 'Medical / Healthcare',
    'summary': 'Emergency Department and In-Patient Department management for HMS',
    'author': 'Bista Solutions',
    'website': 'https://www.bistasolutions.com',
    'license': 'OPL-1',
    'depends': ['acs_hms', 'acs_laboratory'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'views/ward_views.xml',
        'views/bed_views.xml',
        'views/reception_views.xml',
        'views/operation_theatre_views.xml',
        'views/emergency_case_views.xml',
        'views/admission_views.xml',
        'views/nursing_views.xml',
        'views/discharge_views.xml',
        'views/patient_views.xml',
        'views/appointment_views.xml',
        'views/menu_item.xml',
        'report/discharge_summary_report.xml',
        'report/discharge_summary_template.xml',
    ],
    'demo': [
        'demo/emergency_ipd_demo.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
