from . import ward
from . import bed
from . import triage_vitals
from . import emergency_case
from . import appointment
from . import treatment
from . import laboratory
from . import prescription
from . import procedure
from . import admission
from . import nursing
from . import patient
from . import discharge
from . import reception
from . import operation_theatre
from . import lab_request
